# 训练参数配置
task: "sdog"
headless: true
num_envs: 4096
sim_device: "cuda:0"
rl_device: "cuda:0"
max_iterations: 100
change_desc: "test"
play_after_train: true
# 其他可选参数 (注释掉的将使用默认值)
# resume: false
# experiment_name: "my_experiment"
# run_name: "my_run"
# seed: 1