# 训练参数配置
task: "sdog"
headless: true
num_envs: 4096
sim_device: "cuda:0"
rl_device: "cuda:0"
max_iterations: 4500
change_desc: "torques = -0.0002,action_rate = -0.01,dof_pos_limits = -10.0"
# 其他可选参数 (注释掉的将使用默认值)
# resume: false
# experiment_name: "my_experiment"
# run_name: "my_run"
# seed: 1